/** Queryable anomaly / reconciliation flags for PaymentCheckout (JSON array on row). */
export const FINANCIAL_ANOMALY = Object.freeze({
  LOW_MARGIN: 'LOW_MARGIN',
  NEGATIVE_MARGIN: 'NEGATIVE_MARGIN',
  STRIPE_FEE_DIVERGENCE: 'STRIPE_FEE_DIVERGENCE',
  STRIPE_AMOUNT_MISMATCH: 'STRIPE_AMOUNT_MISMATCH',
  PROVIDER_REFERENCE_MISSING: 'PROVIDER_REFERENCE_MISSING',
  PROVIDER_COST_UNVERIFIED: 'PROVIDER_COST_UNVERIFIED',
});
