/** Internal payment / recharge lifecycle (persisted on PaymentCheckout). */
export const PAYMENT_CHECKOUT_STATUS = {
  INITIATED: 'INITIATED',
  CHECKOUT_CREATED: 'CHECKOUT_CREATED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  RECHARGE_PENDING: 'RECHARGE_PENDING',
  RECHARGE_COMPLETED: 'RECHARGE_COMPLETED',
  RECHARGE_FAILED: 'RECHARGE_FAILED',
};
